# Generated by Django 3.0.14 on 2022-12-07 16:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20221207_2116'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=50),
        ),
    ]
