# Generated by Django 4.1.4 on 2022-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20221209_2003'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
